language: python
dist: focal
python:
  - "3.7.9"
  - "3.8"
  - "3.9"
  - "3.10"
jobs:
  include:
    - python: "3.8"
      env:
        - JOB=linting
      install:
        - pip install pre-commit
        - pre-commit install
      script:
        - pre-commit run --all-files
install:
  - pip install poetry
  - poetry install
  - pip install coveralls
script:
  - pytest --cov=reformat_gherkin/
after_success:
  - coveralls
deploy:
  provider: pypi
  username: __token__
  password:
    secure: Mos4EuuXhINiPZwTnY2lAaIepKa0g71eJaEo8APsG6Or/deCI/kgWaboRfqxcQ3jsHkHC0E5xPR9Sh8quGu/BSh9O7a0988X+gjvKBJ48h7JcHElfGnWU2CCMcnQqQs91BOvBQbqt14I2Pm+2G2TDwo+rmNvkvYag2GfwG0GuzyZ6FWQ2vVkuOCafadE5QwODBE7n6NbJfwEovRSd7GVU8CUdw3hYemOcwJ0xNiO3A3iWJydvpmmRtdeOfVpYa19IWuSjAPN2RJ+EqZSRTeSfCZOkTOQMXdm9WuwYdYzdSHj7XZxMGlioWbBTDjS6EFIQMqWI2up2RN0/ierU+hmotJB+wza6reZjb7vnRWTQCPlhK2gpfb5+z3R9tm5NmOCpeeIEO9lK3MGDU/96QlmhWLYmtPky5TWnmF+RNYUouV3IBSCpx9RfIPtUU3s+AdmcMKVo/vPJKmeZu2dqwXvTzU3Ck3bcd+NTz3lFukyT2vvGYLAbepmP1IjdiNGyx4cm6Oj1qXOqTqEr8HaHJvl6BIgqS+SdbfLjPSKWcYvNpvMzOodW0K6EBnkuVnmbQPGw0kQQChY9UwDDeV0qjPk1YKcbUuqYKFdZthgZOd4rH4LVkaI6vdFYYfmlFRZMSSwsg9eZEkPotgE4qwkvDJV4D+N8z0WHuIBJPxV7ga5O9s=
  skip_cleanup: true
  on:
    branch: master
    python: "3.8"
