trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install poetry
    poetry install
  displayName: 'Install dependencies'

- script: |
    pip install flake8
    flake8
  displayName: 'Run lint tests'

- script: |
    pip install pytest pytest-azurepipelines
    pytest --cov=reformat_gherkin/
  displayName: 'Test with pytest'
