trigger:
- master

variables:
  pythonVersions: ["3.6", "3.7"]
  images: ["ubuntu-16.04", "macos-10.13", "vs2017-win2016"]

jobs:
- job: Test
  strategy:
    matrix:
      ${{ each py in variables.pythonVersions }}:
        ${{ each image in variables.images }}:
          ${{ format('{0}{1}', py, os) }}:
            imageName: ${{ image }}
            pythonVersion: ${{ py }}

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      architecture: 'x64'
    displayName: 'Use Python $(pythonVersion)'

  - script: |
      python -m pip install --upgrade pip
      pip install poetry
      poetry install
    displayName: 'Install dependencies'

  - script: |
      pip install flake8
      flake8
    displayName: 'Run lint tests'

  - script: |
      pip install pytest pytest-azurepipelines
      pytest --cov=reformat_gherkin/
    displayName: 'Test with pytest'
