parameters:
  pythonVersions: []
  images: []

jobs:
  - job: Test
    strategy:
      matrix:
        ${{ each py in parameters.pythonVersions }}:
          ${{ each image in parameters.images }}:
            ${{ format('{0}-{1}', py, image) }}:
              imageName: ${{ image }}
              pythonVersion: ${{ py }}

    pool:
      vmImage: $(imageName)

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(pythonVersion)'
          architecture: 'x64'
        displayName: 'Use Python $(pythonVersion)'

      - script: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
        displayName: 'Install dependencies'

      - script: |
          poetry run pip install pytest-azurepipelines
          poetry run pytest --cov --cov-report=xml
        displayName: 'Run unit tests'
