name: Publish package

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
