name: Run tests

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install poetry coveralls
          poetry install

      - name: Run tests
        run: pytest --cov

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: test

  coveralls:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls finished
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel-finished: true
